
# output_dir: /user/liufuxu/project/zBioSynth/output/soluprot/proteincnn1d
output_dir: output/sgrna_offtarget/lm


dataset:
  class: Sgrnaofftarget
  # path: /share/liufuxu/zBioSynth/dataset/promoter/promoter.csv
  path: sgrna_offtarget_v2.csv
  fold: 0
  feat_type: language_model
  data_name: seq
  label_name: label
  max_length: null
  lm_model_name: rnalm_8m
  padding_mode: max_length

task:
  class: SgrnaofftargetPrediction
  criterion: bce
  metric: [ "bce", "acc", "b_acc", "auroc", "mcc", "precision", "f1"]
  normalization: False
  num_mlp_layer: 2
  num_class: 1
  mlp_batch_norm: False
  mlp_dropout: 0.4
  verbose: 0
  model:
    class: RNALM
    model_name: rnalm_8m
    model_path: /share/liufuxu/zBioSynth/resources/pretrained_weights

eval:
  do_eval: True
  eval_epochs: 1
  eval_metric: [ "b_acc" ]
  metric_mode: max


optimizer:
  class: Adam
  lr: 3.0e-4

engine:
  gpus: [0]
  batch_size: 64
  gradient_interval: 1
  num_worker: 4
  log_interval: 1000
  
collate_fn: emb_data_collate

lr_scheduler:
  name: linear
  num_warmup_epochs: 1
  num_epochs: 1
  # num_warmup_epochs: 5
  # num_epochs: 40

mlflow:
  EXPERIMENT: Sgrna-LM
  TRACKING_URI: /user/liufuxu/project/zBioSynth/mlruns
  EXPERIMENT_NAME: Sgrna
  EXPERIMENT_ID: 9          ## the id of the this experiment
  RUN_NAME: RNALM   ## the name of the this run