
output_dir: /user/liufuxu/project/zBioSynth/output/soluprot/proteincnn1d

dataset:
  class: protein_solubility
  path: /share/liufuxu/zBioSynth/dataset/soluprot/soluprot.csv
  fold: 0
  feat_type: language_model
  data_name: seq
  label_name: solubility
  max_length: null
  lm_model_name: esm2_8m
  padding_mode: max_length

task:
  class: ProteinSolubilityPrediction
  criterion: bce
  metric: [ "bce", "b_acc", "acc", "auroc", "mcc", "precision" ]
  normalization: False
  num_mlp_layer: 2
  num_class: 1
  mlp_batch_norm: True
  mlp_dropout: 0.4
  verbose: 0
  model:
    class: Esm2Model
    model_name: esm2_150m

eval:
  do_eval: True
  eval_epochs: 1
  eval_metric: [ "mcc" ]

optimizer:
  class: Adam
  lr: 3.0e-4

engine:
  gpus: [0,1,2,3]
  batch_size: 8
  gradient_interval: 1
  num_worker: 4
  log_interval: 100
  
collate_fn: emb_data_collate

lr_scheduler:
  name: linear
  num_warmup_epochs: 5
  num_epochs: 40